name: Build SONiC for QFX5200
on:
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout SONiC source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a compatible Python version, e.g., 3.9, 3.10, 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gawk curl git-core \
            unzip libssl-dev libelf-dev \
            autoconf automake libtool xz-utils libxml2-utils \
            bc libpci-dev libnl-3-dev libnl-genl-3-dev \
            libdbus-1-dev iproute2 libcap-dev
          # Install jinja2-cli for the 'j2' command.
          pip install jinja2-cli

      - name: Debug j2 installation path
        run: |
          echo "--- Contents of ~/.local/bin ---"
          ls -la ~/.local/bin || echo "~/.local/bin not found or empty."
          echo "--- pip show jinja2-cli ---"
          pip show jinja2-cli || echo "jinja2-cli not found by pip show."
          echo "--- Python user base directory ---"
          python3 -m site --user-base

      - name: Make j2 command globally available and verify
        run: |
          # Ensure the user's local bin directory exists before trying to find/symlink j2
          USER_BIN_DIR="$(python3 -m site --user-base)/bin"
          mkdir -p "$USER_BIN_DIR"
          echo "Ensured directory exists: $USER_BIN_DIR"

          # Find the j2 executable path
          J2_PATH=$(find "$USER_BIN_DIR" -name j2 -type f -executable)
          if [ -z "$J2_PATH" ]; then
            echo "Error: j2 executable not found after pip install. Check pip installation logs and debug output above."
            exit 1
          fi
          echo "Found j2 at: $J2_PATH"

          # Create a symbolic link for 'j2' in /usr/local/bin to ensure it's found by make.
          sudo ln -sf "$J2_PATH" /usr/local/bin/j2
          echo "Symlinked j2 to /usr/local/bin/j2"

          # Verify j2 is now in PATH
          if command -v j2 &> /dev/null; then
            echo "j2 is now found in PATH: $(command -v j2)"
          else
            echo "Error: j2 is still not found in PATH after symlinking. Check symlink target."
            exit 1
          fi

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Ensure user is in Docker group
        run: |
          # Add the current user to the docker group to allow running docker commands without sudo.
          # '|| true' prevents the step from failing if the user is already in the group.
          sudo usermod -aG docker $USER || true
          # 'newgrp docker' activates the new group membership for the current shell session.
          # This is crucial for the subsequent 'make' commands to recognize the new group.
          newgrp docker || true

      - name: Verify Docker access
        run: docker version

      - name: Prepare /var/cache/sonic directory
        run: |
          # Create the /var/cache/sonic directory and set permissions.
          # This addresses the 'Permission denied' error encountered during 'make configure'.
          # Using sudo here as it's a system-level directory creation that requires elevated privileges.
          sudo mkdir -p /var/cache/sonic
          sudo chmod 777 /var/cache/sonic # Setting broad permissions to ensure write access for the runner user

      - name: Debug Dockerfiles
        run: |
          echo "--- Contents of Dockerfile (if exists) ---"
          # Check if Dockerfile exists before trying to cat it
          if [ -f Dockerfile ]; then
            cat Dockerfile
          else
            echo "Dockerfile not found."
          fi
          echo "--- Contents of Dockerfile.cleanup (if exists) ---"
          # Check if Dockerfile.cleanup exists before trying to cat it
          if [ -f Dockerfile.cleanup ]; then
            cat Dockerfile.cleanup
          else
            echo "Dockerfile.cleanup not found or empty."
          fi
          echo "--- Listing files in current directory ---"
          ls -la

      - name: Initialize SONiC build
        run: |
          # 'j2' should now be globally available via the symlink.
          # This step prepares the SONiC build environment.
          make init

      - name: Configure SONiC for QFX5200
        run: |
          # 'j2' should now be globally available via the symlink.
          # 'sudo' was removed previously as per SONiC's requirement.
          make configure PLATFORM=juniper_qfx5200_32c

      - name: Build SONiC
        run: |
          # 'j2' should now be globally available via the symlink.
          # This step initiates the full SONiC build process, which includes
          # building necessary Docker images internally.
          make all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonic-juniper-qfx5200
          path: |
            target/sonic-juniper_qfx5200_32c.bin
            target/sonic-juniper_qfx5200_32c.tar.gz
