name: Build SONiC for QFX5200

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest

    container:
      image: sonicdev-microsoft.azurecr.io/sonic-slave-buster:latest
      options: --user root

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Fix APT for Debian Buster EOL
        run: |
          sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list
          sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list
          sed -i '/^deb.*updates/d' /etc/apt/sources.list
          apt-get update -o Acquire::Check-Valid-Until=false

      - name: Install required tools
        run: |
          apt-get update -o Acquire::Check-Valid-Until=false
          apt-get install -y sudo make g++ curl git

      - name: Configure build
        run: |
          make init
          make configure PLATFORM=juniper_qfx5200_32c

      - name: Build SONiC image
        run: |
          make all
