name: Build SONiC QFX5200 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SONiC
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull and Set Up Docker Environment
        run: |
          docker pull debian:buster

          # Stage 1: Setup container environment as root
          docker run --name sonic-build-setup -v ${{ github.workspace }}:/workspace -w /workspace debian:buster bash -c "
            apt update &&
            apt install -y git make python3 python3-pip curl sudo g++ &&
            groupadd -g 998 docker || true &&
            useradd -m -u 1001 -g 998 builder &&
            chown -R builder:docker /workspace
          "

      - name: Run SONiC Build as builder user
        run: |
          docker commit sonic-build-setup sonic-builder-image

          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace --user 1001:998 sonic-builder-image bash -c "
            git remote set-url origin https://github.com/${{ github.repository }}.git &&
            git fetch origin &&
            make init &&
            make configure PLATFORM=juniper_qfx5200-r0 &&
            make target/sonic-device-image-juniper_qfx5200-r0.bin
          "

      - name: Upload SONiC Image
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
