name: Build SONiC QFX5200 Image

on:
  workflow_dispatch:  # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix Git Remote Tracking (origin)
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch origin

      - name: Install Docker & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker.io python3-pip
          sudo usermod -aG docker $USER

      - name: Create Builder User
        run: |
          sudo useradd -m builder
          sudo usermod -aG docker builder
          sudo chown -R builder:builder .
          echo "builder ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/builder

      - name: Build SONiC QFX5200 Image as builder
        run: |
          sudo -u builder -i bash -c "
            cd $GITHUB_WORKSPACE &&
            make init &&
            make configure PLATFORM=juniper_qfx5200-r0 &&
            make target/sonic-device-image-juniper_qfx5200-r0.bin
          "

      - name: Upload SONiC Image
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
