name: SONiC QFX5200 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sonicdev-microsoft.azurecr.io/sonic-slave-buster:latest
      options: --user root
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Configure and build SONiC for QFX5200
        run: |
          make init
          make configure PLATFORM=juniper_qfx5200-r0
          make target/sonic-juniper_qfx5200-r0.bin
