name: Build SONiC for QFX5200
on:
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest
    # Set environment variables for the entire job
    env:
      # Ensure ~/.local/bin is in PATH for the 'j2' command across all steps
      PATH: ${{ github.home }}/.local/bin:${{ env.PATH }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout SONiC source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gawk curl git-core \
            python3-pip unzip libssl-dev libelf-dev \
            autoconf automake libtool xz-utils libxml2-utils \
            bc libpci-dev libnl-3-dev libnl-genl-3-dev \
            libdbus-1-dev iproute2 libcap-dev
          # Install jinja2-cli for the 'j2' command. It will be installed to ~/.local/bin
          pip install jinja2-cli

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Ensure user is in Docker group
        run: |
          # Add the current user to the docker group to allow running docker commands without sudo.
          # '|| true' prevents the step from failing if the user is already in the group.
          sudo usermod -aG docker $USER || true
          # 'newgrp docker' activates the new group membership for the current shell session.
          # This is crucial for the subsequent 'make' commands to recognize the new group.
          # Note: This command might not fully persist group membership across all steps,
          # but the primary issue of 'sudo' for make has been addressed.
          newgrp docker || true

      - name: Verify Docker access
        run: docker version

      - name: Prepare /var/cache/sonic directory
        run: |
          # Create the /var/cache/sonic directory and set permissions.
          # This addresses the 'Permission denied' error encountered during 'make configure'.
          # Using sudo here as it's a system-level directory creation that requires elevated privileges.
          sudo mkdir -p /var/cache/sonic
          sudo chmod 777 /var/cache/sonic # Setting broad permissions to ensure write access for the runner user

      - name: Initialize SONiC build
        run: |
          # The PATH is now set globally for the job, so explicit export here is less critical
          # but harmless. This step prepares the SONiC build environment.
          make init

      - name: Configure SONiC for QFX5200
        run: |
          # The PATH is now set globally for the job.
          # 'sudo' was removed previously as per SONiC's requirement.
          make configure PLATFORM=juniper_qfx5200_32c

      - name: Build SONiC
        run: |
          # The PATH is now set globally for the job.
          # This step initiates the full SONiC build process, which includes
          # building necessary Docker images internally.
          make all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonic-juniper-qfx5200
          path: |
            target/sonic-juniper_qfx5200_32c.bin
            target/sonic-juniper_qfx5200_32c.tar.gz
