name: Build SONiC for QFX5200

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SONiC source
        uses: actions/checkout@v4

      - name: Set up Docker build env and run build
        uses: addnab/docker-run-action@v3
        with:
          image: sonicdev-microsoft.azurecr.io/sonic-slave-buster:latest
          options: -u 1000 --privileged
          shell: bash
          run: |
            # Fix Debian Buster EOL issues
            sudo sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list
            sudo sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list
            sudo sed -i '/^deb.*updates/d' /etc/apt/sources.list
            sudo apt-get update -o Acquire::Check-Valid-Until=false
            sudo apt-get install -y make g++ curl git

            # Set up build environment
            cd $GITHUB_WORKSPACE
            make init
            make configure PLATFORM=juniper_qfx5200_32c
            make all

            # Copy artifacts for upload
            mkdir -p $GITHUB_WORKSPACE/artifacts
            find ./target -type f \( -name "*.bin" -o -name "*.tar.gz" \) -exec cp {} $GITHUB_WORKSPACE/artifacts/ \;

      - name: Upload built image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonic-build-output
          path: artifacts/
