name: Build SONiC QFX5200 with DUE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SONiC
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker (if not already)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Start SONiC DUE Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/sonic -w /sonic \
            docker.io/sonicdev-microsoft.azurecr.io:sonic-slave-buster \
            bash -c "
              make init &&
              make configure PLATFORM=juniper_qfx5200-r0 &&
              make target/sonic-device-image-juniper_qfx5200-r0.bin
            "

      - name: Upload SONiC QFX5200 Image
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
