name: Build SONiC QFX5200 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Docker & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker.io python3-pip
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Setup Builder User
        run: |
          sudo useradd -m builder
          sudo usermod -aG docker builder
          sudo chown -R builder:builder .
          echo "builder ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/builder

      - name: Run Build as builder
        run: |
          sudo -u builder -i bash -c "
          cd $GITHUB_WORKSPACE &&
          make init &&
          make configure PLATFORM=juniper_qfx5200-r0 &&
          make target/sonic-device-image-juniper_qfx5200-r0.bin
          "

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
