name: Build SONiC for QFX5200

on:
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SONiC source
        uses: actions/checkout@v4

      - name: Set up Docker permission
        run: |
          sudo usermod -aG docker $USER || true
          sudo chown root:docker /var/run/docker.sock || true

      - name: Build SONiC in docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/sonic \
            -w /sonic \
            sonicdev-microsoft.azurecr.io/sonic-slave-buster:latest \
            bash -c "make init && make configure PLATFORM=juniper_qfx5200_32c && make all"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonic-juniper-qfx5200
          path: |
            target/sonic-juniper_qfx5200_32c.bin
            target/sonic-juniper_qfx5200_32c.tar.gz
