name: Build SONiC QFX5200 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker container with builder user
        run: |
          docker pull debian:buster
          docker run --rm -v $(pwd):/workspace \
            -w /workspace \
            -e "DEBIAN_FRONTEND=noninteractive" \
            --user $(id -u):$(id -g) \
            debian:buster bash -c "
              apt update &&
              apt install -y git make python3 python3-pip curl docker.io sudo g++ \
              && groupadd docker || true \
              && useradd -m builder || true \
              && usermod -aG docker builder &&
              chown -R builder:docker /workspace &&
              su builder -c '
                cd /workspace &&
                git remote set-url origin https://github.com/${{ github.repository }}.git &&
                git fetch origin &&
                make init &&
                make configure PLATFORM=juniper_qfx5200-r0 &&
                make target/sonic-device-image-juniper_qfx5200-r0.bin
              '
            "

      - name: Upload SONiC Image
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
