name: Build SONiC QFX5200 Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Dependencies
        run: |
          apk add --no-cache bash git make python3 py3-pip curl
          pip3 install --upgrade pip

      - name: Build SONiC for QFX5200
        run: |
          git config --global --add safe.directory /__w/sonic-buildimage/sonic-buildimage
          make init
          make configure PLATFORM=juniper_qfx5200-r0
          make target/sonic-device-image-juniper_qfx5200-r0.bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonic-qfx5200
          path: target/sonic-device-image-juniper_qfx5200-r0.bin
