name: Build SONiC for QFX5200

on:
  workflow_dispatch:

jobs:
  build-sonic:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout SONiC source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gawk curl git-core \
            python3-pip unzip libssl-dev libelf-dev \
            autoconf automake libtool xz-utils libxml2-utils \
            bc libpci-dev libnl-3-dev libnl-genl-3-dev \
            libdbus-1-dev iproute2 libcap-dev

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Ensure user is in Docker group
        run: |
          sudo usermod -aG docker $USER || true
          newgrp docker || true

      - name: Verify Docker access
        run: docker version

      - name: Initialize SONiC build
        run: |
          make init

      - name: Configure SONiC for QFX5200
        run: |
          make configure PLATFORM=juniper_qfx5200_32c

      - name: Build SONiC
        run: |
          make all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonic-juniper-qfx5200
          path: |
            target/sonic-juniper_qfx5200_32c.bin
            target/sonic-juniper_qfx5200_32c.tar.gz
